on:
  push:
    branches: [main,master]

name: deploy
jobs:
  render:
    name: update-shinyapp-book-pkg
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::pkgdown
            any::fs
            any::rmarkdown
            any::pagedown
            any::remotes
      - name: Install remotes, and the updated package
        run: |
          remotes::install_github("abjur/obsTemplate")
          remotes::install_github("abjur/testeAction", force = TRUE)
        shell: Rscript {0}
      - name: Atualizando Site
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript "inst/update-site.R"
      - name: Atualizando Relatorio
        run: |
          Rscript "inst/update-report.R"
          git checkout -B tmp-branch
          git add -f inst/book/relatorio/*
          git commit -m "Update Relatorio"
          git fetch
          git checkout -f gh-pages
          git checkout tmp-branch -- inst/book/relatorio
          mv inst/book/relatorio docs/
          rm -R inst
          git add -A
          git commit -m "Add relatorio to gh-pages branch"
          git push
          git checkout main
      - name: Atualizando App
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SAT }}
          SHINYAPPS_SECRET: ${{ secrets.SAS }}
          AUTH0_KEY: ${{ secrets.A0K }}
          AUTH0_SECRET: ${{ secrets.A0S }}
        run: |
          Rscript "inst/update-app.R"
