on:
  push:
    branches: [main,master]

name: deploy
jobs:
  render:
    name: update-shinyapp-book-pkg
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::pkgdown
            any::fs
            any::rmarkdown
            any::pagedown
            any::remotes
      - name: Install remotes, and the updated package
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
        run: |
          remotes::install_github("abjur/obsTemplate")
          remotes::install_github("abjur/testeAction", force = TRUE)
        shell: Rscript {0}
      - name: Execute Script
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
          SHINYAPPS_TOKEN: ${{ secrets.SAT }}
          SHINYAPPS_SECRET: ${{ secrets.SAS }}
          AUTH0_KEY: ${{ secrets.A0K }}
          AUTH0_SECRET: ${{ secrets.A0S }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript "inst/update-app.R"
          git checkout gh-pages
          cd docs
          git checkout master -- inst/book/relatorio
          git add relatorio
          git commit -m "Adding 'relatorio' directory from 'master' branch."
          git checkout master
      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          clean: false
          branch: gh-pages
          folder: docs
